# Configurations

# PORT
server:
  port: 8081

# Real db url connection
# url: jdbc:mysql://your-database-host:3306/your_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-update.
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Format SQL queries.
# Loading [environment variables]
#  config:
#    import: "dev.env"
